server:
  port: 3000
application:
  domain: "csb.op"
  name: "Cyber Security Bureau"
  logo: "https://i.imgur.com/tMbGPfi.png"
  favicon: https://mod.gov.ge/assets/img/favicon.ico
  numberOfRandomFakeUsers: 0
  showChallengeSolvedNotifications: true
  showCtfFlagsInNotifications: true
  showChallengeHints: false
  showGitHubRibbon: false
  theme: "sandstone" # Options: cerulean  cosmo  cyborg  darkly  flatly lumen  paper  readable  sandstone  simplex  slate  spacelab  superhero  united  yeti
  twitterUrl: ""
  facebookUrl: "https://www.facebook.com/%E1%83%99%E1%83%98%E1%83%91%E1%83%94%E1%83%A0%E1%83%A3%E1%83%A1%E1%83%90%E1%83%A4%E1%83%A0%E1%83%97%E1%83%AE%E1%83%9D%E1%83%94%E1%83%91%E1%83%98%E1%83%A1-%E1%83%91%E1%83%98%E1%83%A3%E1%83%A0%E1%83%9D-Cyber-Security-Bureau-1374773212835669/"
  recyclePage:
    topProductImage: "Gear-200155340.jpg"
    bottomProductImage: "Gear-200155753.jpg"
products:
  - name: 'OWASP Zed Attack Proxy (ZAP)'
    description: "ZAP is one of the world’s most popular free security tools and can help you automatically find security vulnerabilities while you are developing and testing your applications."
    price: 0.01
    image: 'zap.png'
    useForProductTamperingChallenge: true
  - name: 'Christmas special offer of 2014'
    description: 'სტიკერების ნაკრები'
    price: 29.99
    image: 'undefined.jpg'
    useForChristmasSpecialChallenge: true
  - name: 'Mozilla Austin CTF Logo (3D-printed)'
    description: 'This rare item was designed and handcrafted in Sweden. This is why it is so incredibly expensive despite its complete lack of purpose.'
    price: 99.99
    image: '3d_keychain.jpg' # Exif metadata contains "OpenSCAD" as subtle hint...
    fileForRetrieveBlueprintChallenge: '3d_keychain.stl' # ...to blueprint file type
