server:
  port: 3000
application:
  domain: csb.op
  name: 'Cyber Security Bureau'
  logo: https://i.imgur.com/tMbGPfi.png
  favicon: https://mod.gov.ge/assets/img/favicon.ico
  numberOfRandomFakeUsers: 10
  showChallengeSolvedNotifications: false
  showChallengeHints: false
  showVersionNumber: false
  theme: sandstone # Options: cerulean  cosmo  cyborg  darkly  flatly lumen  paper  readable  sandstone  simplex  slate  spacelab  superhero  united  yeti
  gitHubRibbon: none # Options: darkblue  gray  green  orange  red  white  none
  twitterUrl: null
  facebookUrl: 'https://www.facebook.com/%E1%83%99%E1%83%98%E1%83%91%E1%83%94%E1%83%A0%E1%83%A3%E1%83%A1%E1%83%90%E1%83%A4%E1%83%A0%E1%83%97%E1%83%AE%E1%83%9D%E1%83%94%E1%83%91%E1%83%98%E1%83%A1-%E1%83%91%E1%83%98%E1%83%A3%E1%83%A0%E1%83%9D-Cyber-Security-Bureau-1374773212835669/'
  planetOverlayMap: orangemap2k.jpg
  planetName: Orangeuze
  recyclePage:
    topProductImage: fruit_press.jpg
    bottomProductImage: apple_pressings.jpg
  altcoinName: CSBcoin
  cookieConsent:
    backgroundColor: '#000000'
    textColor: '#ffffff'
    buttonColor: '#afaeae'
    buttonTextColor: '#000000'
    message: 'This website uses cookies to ensure tracking experience.'
    dismissText: 'Me want it!'
    linkText: 'But me wait!'
    linkUrl: 'https://www.youtube.com/watch?v=9PnbKL3wuH4'
  securityTxt:
    contact: 'mailto:info@csb.shop'
    encryption: ~
    acknowledgements: '/#/score-board'
products:
  -
    name: 'Apple Juice (1000ml)'
    price: 1.99
    description: 'The all-time classic.'
    image: apple_juice.jpg
    reviews: # Options 'author': admin, jim, bender, ciso, support, morty, mc.safesearch
      - { text: 'One of my favorites!', author: admin }
  -
    name: 'Raspberry Juice (1000ml)'
    description: 'Made from blended Raspberry Pi, water and sugar.'
    price: 4.99
    image: raspberry_juice.jpg
  -
    name: 'OWASP SSL Advanced Forensic Tool (O-Saft)'
    description: 'O-Saft is an easy to use tool to show information about SSL certificate and tests the SSL connection according given list of ciphers and various SSL configurations.'
    price: 0.01
    image: orange_juice.jpg
    urlForProductTamperingChallenge: 'https://www.owasp.org/index.php/O-Saft'
  -
    name: 'Christmas Super-Surprise-Box (2014 Edition)'
    description: 'Contains a random selection of 10 bottles (each 500ml) of our tastiest juices and an extra fan shirt for an unbeatable price!'
    price: 29.99
    image: undefined.jpg
    useForChristmasSpecialChallenge: true
  -
    name: 'OWASP Juice Shop Sticker (2015/2016 design)'
    description: 'Die-cut sticker with the official 2015/2016 logo. By now this is a rare collectors item. <em>Out of stock!</em>'
    price: 999.99
    image: sticker.png
    deletedDate: '2017-04-28'
  -
    name: 'OWASP Juice Shop-CTF Velcro Patch'
    description: '4x3.5" embroidered patch with velcro backside. The ultimate decal for every tactical bag or backpack!'
    price: 2.92
    image: velcro-patch.jpg
    reviews:
      - { text: 'This thang would look phat on Bobby''s jacked fur coat!', author: mc.safesearch }
      - { text: 'Looks so much better on my uniform than the boring Starfleet symbol.', author: jim }
  -
    name: 'OWASP Juice Shop Logo (3D-printed)'
    description: 'This rare item was designed and handcrafted in Sweden. This is why it is so incredibly expensive despite its complete lack of purpose.'
    price: 99.99
    image: 3d_keychain.jpg # Exif metadata contains "OpenSCAD" as subtle hint...
    fileForRetrieveBlueprintChallenge: JuiceShop.stl # ...to blueprint file type
  -
    name: 'Melon Bike (Comeback-Product 2018 Edition)'
    description: 'The wheels of this bicycle are made from real water melons. You might not want to ride it up/down the curb too hard.'
    price: 2999
    image: melon_bike.jpeg
ctf:
  countryMapping: ~
  showFlagsInNotifications: true
  showCountryDetailsInNotifications: none # Options: none  name  flag  both
  
